### ISSUE TITLE
Feature Request: Support general opacity (for custom themes, and default themes)

### ISSUE THREAD

**Issue by zdzielinski** [warpdotdev/themes#14]
This would be a great feature to have. Generally, I prefer to have a transparent terminal in order to see content in other windows during use. It would be nice to have the ability to specify opacity at a global level, both via yaml customization; and potentially as a "slider" for default themes.

**Comment by elviskahoro** [comment]
@zdzielinski Our mistake for having an issues board for this repo. See this issue for opacity:
- https://github.com/warpdotdev/Warp/issues/17
