### ISSUE TITLE
Feature Request: GUI based theme customization

### ISSUE THREAD

**Issue by zdzielinski** [warpdotdev/themes#15]
This is a bit of a big / long term ask. But having some method of GUI based theme customization would be fantastic. Coming from iterm, it's dead simple to robustly customize my profile and different themes without having to consistently read documentation on settings, values, set hexadecimal colors, etc. Having some sort of intuitive interface to create themes, select colors, specify opacity (raised issue from before) would be a great boost to warp.

**Comment by elviskahoro** [comment]
@zdzielinski just opened an issue in Warp board:
- https://github.com/warpdotdev/Warp/issues/719
