### ISSUE TITLE
 Character under cursor not visible when using catppuccin warp theme + vim

### ISSUE THREAD

**Issue by vneogi199** [warpdotdev/themes#72]
With catppuccin theme here: https://github.com/warpdotdev/themes/blob/main/standard/catppuccin.yaml

<img width="506" alt="image" src="https://github.com/warpdotdev/themes/assets/20491952/d3afb9fa-7b6a-43ef-a29c-90eb91bca92c">

Cursor is at line 2 column 3

<br><br>
With default dark theme:
<img width="499" alt="image" src="https://github.com/warpdotdev/themes/assets/20491952/5458b715-a950-47fe-b6c4-27c1b0285811">

**Comment by 4rc0s** [comment]
I've noticed this on some of my image-generated themes as well. I was looking for a way to change the cursor color in the YAML file but didn't see one.

**Comment by elviskahoro** [comment]
Creating a new issue in our Warp repo!
https://github.com/warpdotdev/Warp/issues/3965
